EXTRA_CFLAGS += -w
#Hotplug place

obj-$(CONFIG_ALUCARD_HOTPLUG) 	+= alucard_hotplug.o
#obj-$(CONFIG_MSM_SLEEPER) 	+= msm_sleeper.o
obj-$(CONFIG_ASMP)		+= autosmp.o
obj-$(CONFIG_BRICKED_HOTPLUG) 	+= bricked_hotplug.o
obj-$(CONFIG_MSM_HOTPLUG) += msm_hotplug.o
obj-$(CONFIG_INTELLI_HOTPLUG) += intelli_hotplug.o

